import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <main className="min-h-screen bg-bg text-text-primary py-16 px-6">
      <article className="max-w-2xl mx-auto">
        <Link to="/" className="text-xs uppercase tracking-[0.3em] text-muted-foreground hover:text-text-primary">← Home</Link>
        <h1 className="font-display italic text-5xl mt-4 mb-8">Terms of Service</h1>
        <p className="text-muted-foreground mb-6">Last updated: June 2026</p>

        <Section title="What ARIA does">
          ARIA gives business suggestions, diagnostics, and growth advice. We do not guarantee specific outcomes — every business is different.
        </Section>
        <Section title="Reports">
          Reports generated by ARIA are guidance, not contractual commitments. Numbers (lead uplift, time saved, ROI) are estimates based on the inputs you provide.
        </Section>
        <Section title="Your responsibility">
          You remain responsible for your own business decisions. Implementation, results, and financial outcomes are yours to own.
        </Section>
        <Section title="Consultation">
          Consultation calls are offered as a courtesy and are optional. We may decline to take on engagements that aren't a fit.
        </Section>
      </article>
    </main>
  );
}
function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-display italic text-2xl mb-2">{title}</h2>
      <p className="text-muted-foreground leading-relaxed">{children}</p>
    </section>
  );
}
